### ISSUE TITLE
点击事件

### ISSUE THREAD

**Issue by zhengyu-android** [dingyi222666/TreeView#10]
1、node.path这个目前是name拼接，如何把name换成depth输出呢
2、我需要点击子节点的箭头实现展示隐藏，而不是整个节点，该如何修改呢

**Comment by dingyi222666** [comment]
1. 没理解
2. 没理解

**Comment by zhengyu-android** [comment]
1、当前treenode：
open class TreeNode<T : Any>(

    var data: T?,

    var depth: Int,

    var path: String = "/root",

    var name: String?,

    var id: Int,

    var hasChild: Boolean = false,

    var isChild: Boolean = false,

    var expand: Boolean = true,
) 

其中的path目前是  targetNode.path = parentNode.path + "/" + targetNode.name
怎么样改成  targetNode.path = parentNode.path + "/" + targetNode. depth  ，这样就能获取当前子节点的位置了

2、我想点击子节点左侧的箭头，让当前节点折叠或者展开，而不是点击整个节点，这样的点击事件如何处理
3、目前支持TreeView支持点击选中吗？如何使用

**Comment by dingyi222666** [comment]
1. 不是很理解为什么要改成 `targetNode.path = parentNode.path + "/" + targetNode. depth` ，还有获取的这是什么子节点的位置？
2. 这个你可以覆盖 ViewHolder 里面的 itemView 的点击事件，这样就不会直接调用 `TreeView#onClick`。然后你在 `TreeViewBinder` 的 `bindView` 里覆盖箭头的相关点击事件，让其调用 `TreeView#onClick` 实现节点的折叠或展开操作。
3. 支持的，你可以去项目的 actions 里 下载 demo apk 体验，具体实现代码建议翻阅 demo 的 activity。

**Comment by zhengyu-android** [comment]
1、我需要获取每个子节点所在的位置处理其他事件。比如每一层[1,2,4,1,7...]
2、已解决
3、您写的方法：长按一个节点单选之后，换一个子节点长按单选并不会有效果

**Comment by dingyi222666** [comment]
1. 你这个指的是在（原始）数据的位置吧？那你应该拿到 data 后自己去做 indexOf。
2. 你可以查看一下 [这里](https://github.com/dingyi222666/TreeView/blob/2661f60df5586d22c5ba64ad7cf904674466d4b8/treeview/src/main/kotlin/io/github/dingyi222666/view/treeview/TreeView.kt#L806)。有几种模式，包括多选，多选（选中子节点），单选，无（不设置选择模式）。你这个换一个子节点长按单选没有效果，那么你设置的是单选还是多选？

**Comment by zhengyu-android** [comment]
2：我设置了单选TreeView.SelectionMode.SINGLE，但是选择一个的时候，选择其他的没反应 ，有什么办法选择其他的，取消上一个选中的，在选择目前选择的。或者有什么方法可以获取选中的node

**Comment by dingyi222666** [comment]
你这个逻辑确实是我没考虑到，后续可能会修改单选模式的逻辑。这几天可能没有空弄哈哈。

**Comment by zhengyu-android** [comment]
拖动子节点，应该是在当前节点下拖动，怎么样才能实现呢

**Comment by dingyi222666** [comment]
不是很理解你的意思。

不过节点拖动的逻辑确实是有问题，主要表现在无法把一个节点拖动进去一个空的字节点上（后续可能的话我会继续改善）

**Comment by zhengyu-android** [comment]
比如拖动一个子节点，只能在当前父节点下，进行拖动，这样更符合逻辑，实现也更简单，也不需要考虑拖动进去一个空的字节点上。这样符合大多数开发设计

**Comment by zhengyu-android** [comment]
你好，有时间更新吗？目前两个问题
1、单选模式下，选中一个节点，取消其他节点的选中状态
2、只能在当前父节点中拖动，不可以拖动到其他节点

**Comment by dingyi222666** [comment]
抱歉，目前这几周还是没有时间呢，忙着其他项目。

如果有能力的话，欢迎 PR。

**Comment by dingyi222666** [comment]
1. 已修复。
2. 可以看一下 `TreeViewBinder#onMoveView`， 能否满足需求？

**Comment by zhengyu-android** [comment]
更新1.3.1版本后，使用refresh（）会闪退（我操作list数据，然后更新Treeview的）
FATAL EXCEPTION: main
                                                                                                    Process: com.iimt.robotarm, PID: 27477
                                                                                                    java.lang.NoSuchMethodError: No static method refresh$default(Lio/github/dingyi222666/view/treeview/TreeView;ZLio/github/dingyi222666/view/treeview/TreeNode;Lkotlin/coroutines/Continuation;ILjava/lang/Object;)Ljava/lang/Object; in class Lio/github/dingyi222666/view/treeview/TreeView; or its super classes (declaration of 'io.github.dingyi222666.view.treeview.TreeView' appears in /data/data/com.iimt.robotarm/code_cache/.overlay/base.apk/classes32.dex)
                                                                                                    	at com.iimt.robotarm.treeview.NewAddTreeNodeKt$updateNode$1.invokeSuspend(NewAddTreeNode.kt:198)

**Comment by zhengyu-android** [comment]
你好
1、更新1.3.1的版本后，使用refresh（）会闪退
2、单选设置后，其他的有时还是不能取消
3、滑动能否正在同一个节点中滑动

**Comment by zhengyu-android** [comment]
当我拖动子节点为什么targetNode只会得到父节点，能不能给我返回targetposition呢，这样我可以使用Collections.swap交换起始终止节点的位置

**Comment by dingyi222666** [comment]
抱歉，目前这几周还是没有时间呢(没有写代码的时间)。

如果有能力的话，欢迎 PR。

**Comment by dingyi222666** [comment]
抱歉，无力继续维护此项目。
