### ISSUE TITLE
Support Leaf of different type than Branch

### ISSUE THREAD

**Issue by shervinkoushan** [dingyi222666/TreeView#5]
Hi,

Thank you for creating this great library! 

Is there a reason the data in a Leaf has to have the same type as the Branch?

```
fun <T : Any> DataSourceScope<T>.Leaf(
    name: String,
    data: T? = null
)
```

**Comment by dingyi222666** [comment]
A possible suggestion is to create a common parent type....
In my use case, for example, displaying a file list, data are all `File`, so they are the same type.
So can you describe your use case scenario?

**Comment by shervinkoushan** [comment]
I have a folder structure with items inside.
Click on folder -> Go to folder view
Click on item -> Go to item details

So they have some different fields. But creating a common parent type should be fine!
