### ISSUE TITLE
How can I disable to collapse of root node?

### ISSUE THREAD

**Issue by lijingdoc** [dingyi222666/TreeView#7]
Thanks for your great library.

I need your help.
I want to disable to collapse of the root node.
It means that the root node should be expanded forever.
Is there any way?

Thanks

**Comment by lijingdoc** [comment]
@dingyi222666 
Could you help me?

**Comment by dingyi222666** [comment]
I don’t have time to develop TreeView recently. I may have to wait a few weeks before I can continue developing.

**Comment by dingyi222666** [comment]
Ok. This is a simple question. 
First, let's expand the root node list when initializing the tree.
```kotlin
treeview.expandUntil(1,true)
// or expandAll
treeview.expandAll(true)
```
Then you need to implement the `TreeViewBinder` and override the `onToggle` method.

The `onToggle` method run after the default action (like expanding or collapsing a node), so you just need to check if the node is the root node in this method, and then set it to force expand.

```kotlin
override fun onToggle(
            node: TreeNode<DataSource<String>>,
            isExpand: Boolean,
            holder: TreeView.ViewHolder
        ) {
    if (node.depth < 1) {
        node.expand = true
    }
}
```

**Comment by lijingdoc** [comment]
Hi, @dingyi222666 
It works well, thanks so much.
