### ISSUE TITLE
Is it not possible to drag between child nodes？

### ISSUE THREAD

**Issue by zhengyu-android** [dingyi222666/TreeView#8]
Hello, is it not possible to drag between child nodes？

**Comment by dingyi222666** [comment]
No, I’m implementing it. It’s an experimental feature.

**Comment by dingyi222666** [comment]
https://github.com/dingyi222666/TreeView/commit/393831458cbf2188a7d0a010d80d06d2da4a0b43

**Comment by zhengyu-android** [comment]
Thank you，Is there a separate interface for refreshing nodes？

**Comment by dingyi222666** [comment]
> Thank you，Is there a separate interface for refreshing nodes？

What does your separate interface mean?

**Comment by zhengyu-android** [comment]
private fun createTree(): Tree<TreeNodeData> {
        return Tree.createTree<TreeNodeData>().apply {
            generator = ItemTreeNodeGenerator(item)
            initTree()
        }
    }
    
    
   1、怎么动态添加与移除子节点
2、如何单独只刷新子节点

**Comment by dingyi222666** [comment]
> private fun createTree(): Tree { return Tree.createTree().apply { generator = ItemTreeNodeGenerator(item) initTree() } }
> 
> 1、怎么动态添加与移除子节点 2、如何单独只刷新子节点

第一点可能比较困难，你需要对真实数据做操作后刷新。（当然也可以使用 DataSource 相关类，但是那个比较麻烦）

第二点的话你可以看[这里](https://github.com/dingyi222666/TreeView/blob/35c427f4ba66a564a0c0e9e1adfa4529d02c8bf8/treeview/src/main/kotlin/io/github/dingyi222666/view/treeview/TreeView.kt#L156)，传的第二个参数就是子节点。

**Comment by dingyi222666** [comment]
已经支持了拖动节点，故此 issue 关闭。但仍然可以继续讨论。

**Comment by zhengyu-android** [comment]
对真实数据做操作后刷新,如果数据量非常大会卡顿吗

**Comment by dingyi222666** [comment]
默认是只刷新展开了的节点（及其往后一级），不会一次加载全部数据（除非你的全部节点都展开了）。

数据量看你的情况，这个实际上是看 RecyclerView 实际能承载的 view 数量了。

**Comment by zhengyu-android** [comment]
lifecycleScope.launch {
                binding.treeView.refresh()
            }
使用这个刷新吗

**Comment by dingyi222666** [comment]
> lifecycleScope.launch { binding.treeView.refresh() } 使用这个刷新吗

是

**Comment by zhengyu-android** [comment]
好的 谢谢你

**Comment by zhengyu-android** [comment]
FATAL EXCEPTION: pool-6-thread-2
    Process: com.iimt.robotarm, PID: 8582
    java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.next(ArrayList.java:860)
        at java.util.AbstractList.hashCode(AbstractList.java:566)
        at com.iimt.robotarm.result.TreeNodeData.hashCode(Unknown Source:81)
        at io.github.dingyi222666.view.treeview.TreeNode.hashCode(treeNodes.kt:108)
        
        点击很多数据很多的话，会这样报错

**Comment by zhengyu-android** [comment]
1、如何重写点击子节点的事件
2、FATAL EXCEPTION: pool-6-thread-2
Process: com.iimt.robotarm, PID: 8582
java.util.ConcurrentModificationException
at java.util.ArrayList$Itr.next(ArrayList.java:860)
at java.util.AbstractList.hashCode(AbstractList.java:566)
at com.iimt.robotarm.result.TreeNodeData.hashCode(Unknown Source:81)
at io.github.dingyi222666.view.treeview.TreeNode.hashCode(treeNodes.kt:108)

    添加很多数据的话，会这样报错

**Comment by dingyi222666** [comment]
1. 重写 TreeNodeEventListener#onClick
2. 麻烦详细提供一下相关错误，日志，复现代码。并新开一个 issue 描述该问题

**Comment by zhengyu-android** [comment]
怎么拖动子节点并更新数据呢？
